name: 🖼 Slack Avatar Switcher

on:
  schedule:
    - cron: "0 7  * * 1-5"
    - cron: "0 11 * * 1-5"
    - cron: "0 12 * * 1-5"
    - cron: "0 16 * * 1-5"
    - cron: "0 4  * * 6,0"
  workflow_dispatch:

jobs:
  switch-avatar:
    name: Switch Slack Avatar & Status
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          

      - name: Install dependencies
        run: pip install slack-sdk python-dotenv

      - name: Run avatar switcher
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
        run: python avatar_switcher.py